
import numpy as np
import astropy
from astropy.io import fits
from bisect import bisect_left
from scipy.special import erf
from scipy.interpolate import RegularGridInterpolator, interp1d
import itertools
import os

from dynesty import NestedSampler

import sys, os
sys.path.append(os.path.expanduser('~/Desktop/Pangal'))

from .image import Image
from .spectrum import Spectrum
from .filter import Filter, map_filter_names, nice_filter_names, default_plot_scale_lims, default_plot_units, default_cmaps



# UTILS
# Base directory containing the “DISKEVOL.RES_L0.05_V*” files
this_dir = os.path.dirname(os.path.abspath(__file__))

# Construct full path to the data directory
data_dir = os.path.join(this_dir, ".", "data")
data_dir = os.path.normpath(data_dir)



def load_spectrum_models_from_fits(filename):
    with fits.open(filename) as hdul:
        # Wavelength array from primary HDU
        wl,resolution = hdul[0].data
        nmodels = len(hdul) - 1

        models = []
        for i in range(1, len(hdul)):
            data = hdul[i].data
            header = hdul[i].header


            spec = Spectrum(wl=wl,resolution=resolution,) #flux=data["FLUX"])

            spec.flux_young = data["FLUX_YOUNG"]
            spec.flux_old   = data["FLUX_OLD"]
            
            # Keep the model's metadata
            spec.header.update(header)

            models.append(spec)

    return models






#Load and process precomputed nebular emission line tables from Byler et al. models.

#This function reads tabulated emission line luminosities (in erg/s per ionizing photon)
#for a given metallicity and emission model (2017 or 2018), and convolves the lines with
#the desired spectral resolution and wavelength grid. The resulting emission line spectra 
#are suitable for adding to stellar SEDs generated by codes like CIGALE.

#The lines are modeled as Gaussians, and the convolution simulates how they would appear
#in an observed spectrum, taking into account the resolution and pixel binning. An 
#interpolation function is returned, allowing the user to compute the full nebular 
#emission spectrum for any given ionization parameter and stellar population age.

def load_nebular_tables(self, wl, resolution, emimetal, emimodel):
    """
    Returns:
      nebular_emission_spectrum(ion, age) -> broadened+binned nebular spectrum on wl grid  (n_wl,)
      nebular_line_scales(ion, age)       -> per-line integrated strengths (temp_emm_scales) (n_lines,)
      emm_wls                             -> line wavelengths (vacuum) (n_lines,)
      emm_ions, emm_ages                  -> grids
      emm_scales                          -> raw grid table (n_ions, n_ages, n_lines)
    """

    c_kms = 2.99792458e5  # km/s

    # ---- Pick which Byler file ----
    if emimodel == 'nebular_Byler_mist_2018.lines':
        byler_bins = [382, 9, 7]
        byler_fname = 'nebular_Byler_mist_2018.lines'
        metallist = np.array([6.3245e-05,2.0000e-04,3.5565e-04,6.3245e-04,1.1246e-03,2.0000e-03,
                              3.5565e-03,6.3245e-03,1.1246e-02,2.000e-02,3.5565e-02,6.3245e-02])
        metalstrg = np.array(['-2.5000e+00','-2.0000e+00','-1.7500e+00','-1.5000e+00','-1.2500e+00','-1.0000e+00',
                              '-7.5000e-01','-5.0000e-01','-2.5000e-01','0.0000e+00','2.5000e-01','5.0000e-01'])
    else:
        byler_bins = [128, 10, 7]
        byler_fname = 'nebular_Byler_mist_2017.lines'
        metallist = np.array([0.00020,0.00063246,0.00209426,0.00526054,0.00814761,0.01002374,
                              0.01261915,0.01588656,0.02,0.02517851,0.03169786])
        metalstrg = np.array(['-1.9800e+00','-1.5000e+00','-9.8000e-01','-5.8000e-01','-3.9000e-01','-3.0000e-01',
                              '-2.0000e-01','-1.0000e-01','0.0000e+00','1.0000e-01','2.0000e-01'])

    print("Loading nebular lines templates from", byler_fname)

    # ---- Allocate ----
    emm_scales = np.zeros((byler_bins[2], byler_bins[1], byler_bins[0]), dtype=float)  # (n_ion, n_age, n_lines)
    emm_wls    = np.zeros(byler_bins[0], dtype=float)  # (n_lines,)
    emm_ages   = np.zeros(byler_bins[1], dtype=float)  # (n_age,)
    emm_ions   = np.zeros(byler_bins[2], dtype=float)  # (n_ion,)

    metind = np.argmin(np.abs(metallist - emimetal))
    print(f"Emission line metallicity requested {emimetal}, found {metallist[metind]:5.4f}")
    emimetal = metallist[metind]

    file_path = os.path.join(data_dir, byler_fname)

    icnt, rline, iline = 0, 0, 0

    with open(file_path, 'r') as file:
        for line in file:
            if not line or line[0] == '#':
                continue

            temp = line.strip().split()

            if not iline:
                # first data row: wavelengths of lines
                emm_wls[:] = np.array(temp, dtype=float)
                iline = 1
                continue

            if rline:
                # line fluxes row
                # Byler tables are usually in Lsun per Q(H) or similar; you used Lsun->erg/s factor already
                emm_scales[icnt % byler_bins[2], icnt // byler_bins[2], :] = np.array(temp, dtype=float) * 3.839e33
                icnt += 1

            if len(temp) == 3 and temp[0] == metalstrg[metind]:
                rline = 1
                emm_ages[icnt // byler_bins[2]] = float(temp[1]) / 1e6  # Myr
                emm_ions[icnt % byler_bins[2]]  = float(temp[2])
            else:
                rline = 0

    print(f"Tabulated gas ages (Myr): {emm_ages}")
    print(f"Tabulated ionization grid: {emm_ions}")

    # ---- Filter weirdly long wavelengths (as you had) ----
    keep = (emm_wls < 1e5)
    emm_wls = emm_wls[keep]
    emm_scales = emm_scales[:, :, keep]  # (n_ion, n_age, n_lines_kept)

    n_lines = len(emm_wls)

    # ============================================================
    # (A) Photometry/SED product: pre-broadened, binned spectra on wl
    # ============================================================

    wl = np.asarray(wl, float)
    resolution = np.asarray(resolution, float)

    # pixel edges in wl (linear grid assumed; if not, edges still fine from diffs)
    dpix = np.diff(wl)
    wl_edges = np.r_[wl[0] - dpix[0]/2.0, wl[1:] - dpix/2.0, wl[-1] + dpix[-1]/2.0]

    # instrumental sigma_lambda for each line from R(λ): FWHM=λ/R, sigma=FWHM/2.355
    delta_lambda = wl / resolution
    sigma_line_lambda = np.interp(emm_wls, wl, delta_lambda) / 2.355  # (n_lines,)

    emm_lines_all = np.zeros((len(emm_ions), len(emm_ages), len(wl)), dtype=float)

    for j_ion in range(len(emm_ions)):
        for i_age in range(len(emm_ages)):
            this_scale = emm_scales[j_ion, i_age, :]  # (n_lines,)
            # integrate gaussian over each pixel bin via CDF difference
            prof = np.diff(
                0.5 * (1.0 + erf((wl_edges[None, :] - emm_wls[:, None]) /
                                 (np.sqrt(2.0) * sigma_line_lambda[:, None]))),
                axis=1
            ) / np.diff(wl_edges)[None, :]
            emm_lines_all[j_ion, i_age, :] = np.sum(this_scale[:, None] * prof, axis=0)

    nebular_spec_interp = RegularGridInterpolator(
        points=(emm_ions, emm_ages),
        values=emm_lines_all,
        bounds_error=False,
        fill_value=0.0
    )

    def nebular_emission_spectrum(ion, age):
        return nebular_spec_interp(np.array([[ion, age]]))[0]  # (n_wl,)

    # ============================================================
    # (B) Spectroscopy product: per-line integrated strengths temp_emm_scales
    # ============================================================

    # Here we interpolate the *line strengths* directly:
    # emm_scales has shape (n_ion, n_age, n_lines)
    line_scale_interp = RegularGridInterpolator(
        points=(emm_ions, emm_ages),
        values=emm_scales,   # NOTE: returns (n_lines,) vector
        bounds_error=False,
        fill_value=0.0
    )

    def nebular_line_scales(ion, age):
        return line_scale_interp(np.array([[ion, age]]))[0]  # (n_lines,)

    print("Loading of nebular lines templates completed.")

    return (nebular_emission_spectrum,
            nebular_line_scales,
            emm_wls, emm_ions, emm_ages,)







def load_dust_emission_models(self, wl, dustemimodel):
    """
    Loads dust emission templates from Dale & Helou 2002 (dustemimodel = 'dh02') and return a function of alpha
    or Draine & Li 2014 (dustemimodel = 'dl14'), interpolated on the input wavelength grid.
    """

    alpha_file = os.path.join(data_dir, f'alpha_{dustemimodel}.dat')
    spectra_file = os.path.join(data_dir, f'spectra_{dustemimodel}.dat')

    # Check files exist
    if not os.path.exists(alpha_file):
        raise FileNotFoundError(f"Missing file: {alpha_file}")
    if not os.path.exists(spectra_file):
        raise FileNotFoundError(f"Missing file: {spectra_file}")

    #print(f"Loading dust emission templates from: {alpha_file}")

    # Load alpha values and spectra
    dustem_alpha = np.loadtxt(alpha_file, usecols=(0,))
    dustem_wl = np.loadtxt(spectra_file, usecols=(0,)) * 1e4  # assuming microns to Angstroms
    full_spectra = np.loadtxt(spectra_file)

    # Initialize template matrix
    tdustem = np.zeros((len(dustem_alpha), len(wl)), dtype=float)

    for ii in range(len(dustem_alpha)):
        tdust = 10 ** full_spectra[:, ii + 1]  # column 1 is wavelength, so ii+1
        tdustem[ii, :] = np.interp(wl, dustem_wl, tdust, left=0.0, right=0.0) / wl

    # Normalize each template to Lbol = 1
    norm = np.trapz(tdustem, wl, axis=1)
    tdustem /= norm[:, None]

    dustem_func = interp1d(dustem_alpha, tdustem, axis=0, bounds_error=True)

    # Define a function for convenience
    def dust_emission_spectrum(alpha):
        return dustem_func(alpha)

    print(f"Tabulated alpha values from 'alpha_{dustemimodel}.dat': {dustem_alpha}")
    print("Loading of dust emission templates completed.")

    return dust_emission_spectrum, dustem_alpha




def model_grid_interpolator(self, model_list, param_names):
    """
    Build N-dimensional interpolators for young and old fluxes on the model grid,
    and return callables that output spectra resampled onto self.model_wl.
    """

    # Native (short) wavelength grid from SPS models
    short_wl = np.array(model_list[0].wl, dtype=float)

    # --- Step 1: Build param space ---
    param_tuples = []
    param_to_model = {}
    for model in model_list:
        try:
            values = tuple(float(model.header[k]) for k in param_names)
        except KeyError as e:
            raise KeyError(f"Model is missing parameter {e} in header.")
        param_tuples.append(values)
        param_to_model[values] = model

    # --- Step 2: Build grid axes ---
    grid_axes = [np.array(sorted(set(p[i] for p in param_tuples)), dtype=float)
                 for i in range(len(param_names))]

    # --- Step 3: Allocate grids ---
    grid_shape = tuple(len(ax) for ax in grid_axes)
    n_wl = np.asarray(model_list[0].flux_young).size

    flux_young_grid = np.zeros(grid_shape + (n_wl,), dtype=float)
    flux_old_grid   = np.zeros(grid_shape + (n_wl,), dtype=float)

    # --- Step 4: Fill the grids (store flux per unit mass, like mcspf) ---
    for idxs in np.ndindex(*grid_shape):
        key = tuple(grid_axes[i][idxs[i]] for i in range(len(grid_axes)))
        model = param_to_model[key]
        mstar = float(model.header["MSTAR"])  # you said: linear in FITS
        flux_young_grid[idxs] = np.asarray(model.flux_young, dtype=float) / mstar
        flux_old_grid[idxs]   = np.asarray(model.flux_old,   dtype=float) / mstar

    # --- Step 5: Build interpolators on the native wavelength grid ---
    interp_young = RegularGridInterpolator(
        points=grid_axes, values=flux_young_grid,
        bounds_error=True, fill_value=None
    )
    interp_old = RegularGridInterpolator(
        points=grid_axes, values=flux_old_grid,
        bounds_error=True, fill_value=None
    )

    # --- Wrappers: interpolate in parameter space, then resample in wavelength to self.model_wl ---
    def _check_bounds(x):
        for i, val in enumerate(x):
            if val < grid_axes[i][0] or val > grid_axes[i][-1]:
                raise ValueError(
                    f"Parameter '{param_names[i]}'={val} is outside grid range "
                    f"[{grid_axes[i][0]}, {grid_axes[i][-1]}]"
                )

    def interp_flux_young(**kwargs):
        x = [float(kwargs[name]) for name in param_names]
        _check_bounds(x)

        # RGI wants (n_points, ndim)
        spec_short = interp_young(np.array([x], dtype=float))[0]  # (n_wl,)

        # Resample to the extended wavelength grid, matching mcspf left/right=0 behavior
        return np.interp(self.model_wl, short_wl, spec_short, left=0.0, right=0.0)

    def interp_flux_old(**kwargs):
        x = [float(kwargs[name]) for name in param_names]
        _check_bounds(x)

        spec_short = interp_old(np.array([x], dtype=float))[0]
        return np.interp(self.model_wl, short_wl, spec_short, left=0.0, right=0.0)

    return interp_flux_young, interp_flux_old, grid_axes, short_wl






# Dust attenuation curve based on Calzetti et al. (2000) law
# wl must be in Angstrom
# Takes in imput an array of wavelengths and returns the attenuation function

def dust_attenuation_curve(self, leitatt: bool = False, uv_bump: bool = False):
    """
    return 0.4 * k_cal / R_V
    k_cal is the Calzetti (2000) selective attenuation curve with:
    - optional Leitherer (2002) replacement below 1500 Å
    - optional 2175 Å bump (Drude profile)
    The returned function accepts scalar or array wavelengths in Angstrom.
    """

    R_V = 4.05

    def k_lambda(wl):
        wl = np.asarray(wl, dtype=float)

        k_cal = np.zeros_like(wl, dtype=float)

        # Calzetti+ 2000: piecewise at 6300 Å
        m_long = wl >= 6300.0
        m_short = ~m_long

        # Longer than 6300 Å
        if np.any(m_long):
            k_cal[m_long] = 2.659 * (-1.857 + 1.04 * (1e4 / wl[m_long])) + R_V

        # Shorter than 6300 Å
        if np.any(m_short):
            x = 1e4 / wl[m_short]
            k_cal[m_short] = 2.659 * (-2.156 + 1.509 * x - 0.198 * x**2 + 0.011 * x**3) + R_V

        # Optional Leitherer (2002) below 1500 Å
        if leitatt:
            m_uv = wl < 1500.0
            if np.any(m_uv):
                w = wl[m_uv]
                k_cal[m_uv] = (5.472 + 0.671e4 / w - 9.218e5 / w**2 + 2.620e9 / w**3)

        # Enforce non-negative attenuation pointwise
        k_cal = np.maximum(k_cal, 0.0)

        # Optional 2175 Å bump (Drude-like profile)
        if uv_bump:
            eb = 1.0
            bump = eb * (wl * 350.0) ** 2 / ((wl**2 - 2175.0**2) ** 2 + (wl * 350.0) ** 2)
            k_cal = k_cal + bump

        # Return 0.4 * A(lam)/A(V)
        return 0.4 * k_cal / R_V

    return k_lambda
